-- ============================================================================
-- KOOLEE - Smart Fridge Tracker Database Schema
-- ============================================================================
-- Project: IoT Smart Fridge Monitoring System
-- Database: Supabase PostgreSQL
-- Date: November 23, 2025
-- Description: Complete database schema for ESP32 sensor data, buzzer control,
--              and push notification history
-- ============================================================================

-- ============================================================================
-- TABLE 1: telemetry (Sensor Data Storage)
-- ============================================================================
-- Purpose: Store temperature, humidity, and weight readings from ESP32
-- Update Frequency: Every 10 seconds from ESP32
-- Retention: Unlimited (consider adding cleanup policy for production)

CREATE TABLE IF NOT EXISTS telemetry (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  temperature FLOAT NOT NULL,
  humidity FLOAT NOT NULL,
  weight FLOAT NOT NULL
);

-- Add indexes for performance
CREATE INDEX IF NOT EXISTS idx_telemetry_created_at ON telemetry(created_at DESC);

-- Add comments for documentation
COMMENT ON TABLE telemetry IS 'Stores sensor readings from ESP32: temperature (°C), humidity (%), weight (grams)';
COMMENT ON COLUMN telemetry.temperature IS 'Temperature in Celsius from DHT11 sensor';
COMMENT ON COLUMN telemetry.humidity IS 'Relative humidity percentage from DHT11 sensor';
COMMENT ON COLUMN telemetry.weight IS 'Weight in grams from HX711 load cell';

-- ============================================================================
-- TABLE 2: control (Buzzer Control)
-- ============================================================================
-- Purpose: Control buzzer state and mode (auto/manual override)
-- Access: ESP32 reads every 10s, Flutter app updates via UI, Edge Function updates in auto mode

CREATE TABLE IF NOT EXISTS control (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  buzzer_active BOOLEAN DEFAULT false NOT NULL,
  buzzer_mode VARCHAR(20) DEFAULT 'auto' NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  CONSTRAINT buzzer_mode_check CHECK (buzzer_mode IN ('auto', 'manual_on', 'manual_off'))
);

-- Add comments
COMMENT ON TABLE control IS 'Controls buzzer behavior with auto/manual modes';
COMMENT ON COLUMN control.buzzer_active IS 'Current buzzer state: true = ON, false = OFF';
COMMENT ON COLUMN control.buzzer_mode IS 'Control mode: auto (system), manual_on (force ON), manual_off (force OFF)';

-- Insert default record (ID=1, buzzer OFF, auto mode)
INSERT INTO control (id, buzzer_active, buzzer_mode, updated_at) 
VALUES (1, false, 'auto', timezone('utc'::text, now()))
ON CONFLICT (id) DO NOTHING;

-- ============================================================================
-- TABLE 3: notifications (Push Notification History)
-- ============================================================================
-- Purpose: Store history of push notifications sent via Firebase Cloud Messaging
-- Source: Edge Function saves notifications here after sending FCM

CREATE TABLE IF NOT EXISTS notifications (
  id BIGSERIAL PRIMARY KEY,
  title TEXT NOT NULL,
  body TEXT NOT NULL,
  data JSONB DEFAULT '{}'::jsonb,
  is_read BOOLEAN DEFAULT false NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Add indexes for faster queries
CREATE INDEX IF NOT EXISTS idx_notifications_created_at ON notifications(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_notifications_is_read ON notifications(is_read);

-- Add comments
COMMENT ON TABLE notifications IS 'Stores push notification history from Firebase Cloud Messaging';
COMMENT ON COLUMN notifications.title IS 'Notification title shown to user';
COMMENT ON COLUMN notifications.body IS 'Notification message body';
COMMENT ON COLUMN notifications.data IS 'Additional data (sensor values, problems detected)';
COMMENT ON COLUMN notifications.is_read IS 'Read status: false = unread, true = read';

-- ============================================================================
-- ROW LEVEL SECURITY (RLS) CONFIGURATION
-- ============================================================================
-- Note: RLS disabled for telemetry & control to allow direct ESP32 access
-- RLS enabled for notifications with public policy for simplicity

-- Disable RLS for ESP32 tables (allows unauthenticated access)
ALTER TABLE telemetry DISABLE ROW LEVEL SECURITY;
ALTER TABLE control DISABLE ROW LEVEL SECURITY;

-- Enable RLS for notifications (can be restricted later with auth)
ALTER TABLE notifications ENABLE ROW LEVEL SECURITY;

-- Create policy to allow all operations on notifications (adjust for production)
DO $$ 
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies 
    WHERE tablename = 'notifications' 
    AND policyname = 'Allow all operations on notifications'
  ) THEN
    CREATE POLICY "Allow all operations on notifications" ON notifications
      FOR ALL
      USING (true)
      WITH CHECK (true);
  END IF;
END $$;

-- ============================================================================
-- WEBHOOK CONFIGURATION (Manual Setup Required)
-- ============================================================================
-- To enable automatic threshold detection and buzzer control:
-- 1. Go to Supabase Dashboard → Database → Webhooks
-- 2. Create new webhook:
--    - Name: telemetry_webhook
--    - Table: telemetry
--    - Events: INSERT
--    - Type: HTTP Request
--    - Method: POST
--    - URL: https://[project-ref].supabase.co/functions/v1/push-notification
--    - Headers:
--      * Content-Type: application/json
--      * Authorization: Bearer [your-anon-key]
--
-- This webhook triggers the Edge Function on every new sensor data insert,
-- enabling real-time threshold checking and automatic notifications.

-- ============================================================================
-- VERIFICATION QUERIES
-- ============================================================================

-- Check table structures
SELECT 
  table_name,
  column_name,
  data_type,
  is_nullable,
  column_default
FROM information_schema.columns
WHERE table_name IN ('telemetry', 'control', 'notifications')
ORDER BY table_name, ordinal_position;

-- Check control table initial state
SELECT * FROM control WHERE id = 1;

-- Check indexes
SELECT 
  tablename,
  indexname,
  indexdef
FROM pg_indexes
WHERE tablename IN ('telemetry', 'control', 'notifications')
ORDER BY tablename;

-- ============================================================================
-- SAMPLE DATA (Optional - for testing)
-- ============================================================================

-- Insert sample telemetry data
INSERT INTO telemetry (temperature, humidity, weight) VALUES
  (29.5, 65.2, 1500.0),
  (30.1, 67.8, 1520.0),
  (28.9, 64.5, 1480.0);

-- Insert sample notification
INSERT INTO notifications (title, body, data, is_read) VALUES
  ('⚠️ PERINGATAN KULKAS!', 
   'Terdeteksi masalah: Suhu abnormal (34°C).', 
   '{"temperature": 34, "humidity": 65, "weight": 1500, "problems": ["Temperature too high"]}',
   false);

-- ============================================================================
-- MAINTENANCE QUERIES (Optional)
-- ============================================================================

-- Clean old telemetry data (older than 30 days)
-- DELETE FROM telemetry WHERE created_at < NOW() - INTERVAL '30 days';

-- Mark all notifications as read
-- UPDATE notifications SET is_read = true WHERE is_read = false;

-- Reset buzzer to auto mode
-- UPDATE control SET buzzer_mode = 'auto', buzzer_active = false WHERE id = 1;

-- ============================================================================
-- END OF SCHEMA
-- ============================================================================